- id: prettypst
  name: prettypst
  description: Format files with prettypst
  entry: bash -c 'for x in "$@"; do echo "$x" && prettypst "$x"; done' --
  language: rust
  types: [file]
  files: \.typ$
